apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: image-shop-deployment
  name: image-shop-deployment
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: image-shop-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
