apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: image-account-deployment
  name: image-account-deployment
spec:
  ports:
  - port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: image-account-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
