apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: image-payment-deployment
  name: image-payment-deployment
spec:
  ports:
  - port: 8004
    protocol: TCP
    targetPort: 8004
  selector:
    app: image-payment-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
