apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: image-basket-deployment
  name: image-basket-deployment
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: image-basket-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
