apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: image-ui-deployment
  name: image-ui-deployment
spec:
  ports:
  - port: 8005
    protocol: TCP
    targetPort: 3000
  selector:
    app: image-ui-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
